language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
install:
  - yarn
